/* Auto-generated by genmsg_cpp for file /home/sam/ros_workspace/Cplusplus/RosDispatcher/msg/movement.msg */
#ifndef ROSDISPATCHER_MESSAGE_MOVEMENT_H
#define ROSDISPATCHER_MESSAGE_MOVEMENT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace RosDispatcher
{
template <class ContainerAllocator>
struct movement_ {
  typedef movement_<ContainerAllocator> Type;

  movement_()
  : x(0)
  , y(0)
  {
  }

  movement_(const ContainerAllocator& _alloc)
  : x(0)
  , y(0)
  {
  }

  typedef uint8_t _x_type;
  uint8_t x;

  typedef uint8_t _y_type;
  uint8_t y;


private:
  static const char* __s_getDataType_() { return "RosDispatcher/movement"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "727012f6868afa655d78dc8b436d2c91"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint8 x\n\
uint8 y\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    return size;
  }

  typedef boost::shared_ptr< ::RosDispatcher::movement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RosDispatcher::movement_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct movement
typedef  ::RosDispatcher::movement_<std::allocator<void> > movement;

typedef boost::shared_ptr< ::RosDispatcher::movement> movementPtr;
typedef boost::shared_ptr< ::RosDispatcher::movement const> movementConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::RosDispatcher::movement_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::RosDispatcher::movement_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace RosDispatcher

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::RosDispatcher::movement_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::RosDispatcher::movement_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::RosDispatcher::movement_<ContainerAllocator> > {
  static const char* value() 
  {
    return "727012f6868afa655d78dc8b436d2c91";
  }

  static const char* value(const  ::RosDispatcher::movement_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x727012f6868afa65ULL;
  static const uint64_t static_value2 = 0x5d78dc8b436d2c91ULL;
};

template<class ContainerAllocator>
struct DataType< ::RosDispatcher::movement_<ContainerAllocator> > {
  static const char* value() 
  {
    return "RosDispatcher/movement";
  }

  static const char* value(const  ::RosDispatcher::movement_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::RosDispatcher::movement_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 x\n\
uint8 y\n\
\n\
";
  }

  static const char* value(const  ::RosDispatcher::movement_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::RosDispatcher::movement_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::RosDispatcher::movement_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct movement_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RosDispatcher::movement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::RosDispatcher::movement_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.y);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROSDISPATCHER_MESSAGE_MOVEMENT_H

